sku:
  name: GP_S_Gen5_2
  tier: GeneralPurpose
  family: Gen5
  capacity: 2
maxSizeBytes: 34359738368
autoPauseDelay: 60
minCapacity: '0.5'
requestedBackupStorageRedundancy: Local
useFreeLimit: true
