trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/resources/database/**

variables:
  - template: 'infra/env-config.yml'

stages:
  - stage: DeployDatabase
    displayName: 'Deploy Database'
    jobs:
      - job: Deploy
        displayName: 'Deploy Database Job'
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureServiceConnection)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/infra/resources/database/main.bicep'
              csmParametersFile: '$(System.DefaultWorkingDirectory)/infra/resources/database/main.bicepparam'
            displayName: 'Deploy Database Bicep'
